name: Static Web App build & deploy - Website-Production
on:
  release:
    types: [published]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: jefponte.com
          username: uniselec-api-staging@jefponte.com
          password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}